### ISSUE TITLE
Very loose condition for drw

### ISSUE THREAD

**Issue by sabrehagen** [tracespace/whats-that-gerber#15]
Hi,

Your test for a `drw` file matches any string. This means that a filename of 'asdfasdfa' gets matched as a `drw` file. How come you picked such a loose test condition? I was planning to use `whats-that-gerber` to identify if a filename was a gerber file or not, however in the library's current state it will report any filename is a `drw` file.

```
  {
    id: 'drw',
    name: {
      en: 'gerber drawing'
    },
    match: /.*/
  }
```

**Comment by mcous** [comment]
Hey! So the problem is that this library has always been used in a manner where any filename given is already assumed to be a Gerber file, and we need to identify which type of gerber it is. With that usage, "gerber drawing" is a catch-all, analogous to "unknown gerber type".

Unfortunately, Gerber file extensions that aren't `.gbr` are non-standard according to the [Gerber file spec](https://www.ucamco.com/files/downloads/file/81/the_gerber_file_format_specification.pdf), and just generally, there's no way to definitively say a file is a Gerber or not from just the filename. 

Still, some additions to the API could make this whole thing more palatable to you. Do either of these sound helpful?

1. A static method `whatsThatGerber.isGerber(filename)` that returns `true` if it matches any filetype that isn't the catch-all, `false` otherwise
2. Add an options object to the primary export: `whatsThatGerber(filename, {allowUnknown: false})` that will return an empty string if the filename doesn't match something we recoginze

Either of these would be equivalent to doing:

``` js
function maybeIsGerber (filename) {
  return whatsThatGerber(filename) !== 'drw'
}
```

This would run the risk of returning a false negative if a real Gerber file is named in a way we haven't encountered before.

**Comment by sabrehagen** [comment]
`This would run the risk of returning a false negative if a real Gerber file is named in a way we haven't encountered before.`

True, however the likelihood of a false negative is much lower than a false positive I believe. You seem to have thoroughly covered the common extensions of gerber files, so the likelihood of a false negative is exceedingly low. Conversely, any file type that isn't expected will be incorrectly classed as a `drw` file, which is almost always a false positive.

I appreciate this is a grey area. I'll leave it up to you to decide. The static method you proposed in `1` would be most useful for me.

**Comment by mcous** [comment]
> True, however the likelihood of a false negative is much lower than a false positive I believe. You seem to have thoroughly covered the common extensions of gerber files, so the likelihood of a false negative is exceedingly low

I have seen enough valid Gerber files go through whats-that-gerber and come out as `drw` (i.e. unknown) that I would be nervous about relying on it as a definitive thing. Regardless, though, I'm happy to add the API described in (1). I'd also accept a (non-API-breaking) PR for either (1) or (2) or anything else that helps you!

**Comment by kasbah** [comment]
> the likelihood of a false negative is exceedingly low. Conversely, any file type that isn't expected will be incorrectly classed as a drw file, which is almost always a false positive.

The convention makes sense in the context of it's applications: 
- [pcb-stackup](https://github.com/tracespace/pcb-stackup): will ignore any `drw` files anyway because they are not part of the PCB.
- [viewer.tracespace.io](http://viewer.tracespace.io):  will want to draw any files if there is the slightest chance that they are Gerbers.
